[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet src/Services/ProspectFinderPro.DataIngestion/bin/Release/net8.0/ProspectFinderPro.DataIngestion.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "prospectfinder-api"